language: cpp
sudo: required
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libunittest++-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../

script:
  - make -j4
  - ./tests/unittest-Variable
